### ISSUE TITLE
MMQTTException: MiniMQTT is not connected

### ISSUE THREAD

**Issue by briandye** [VynDesign/message-board#1]
Everything looks good on homeassistant and I can see the MQTT message being published using MQTT explorer. I cant connect to the MQTT broker with the Matrix Portal. I have configured everything per the README -- the bellow error message is what I am getting. I am running on Adafruit CircuitPython 7.3.3.  Do I need to be on the version you built on? Traceback error message below

`Connected to wifi
Traceback (most recent call last):
  File "code.py", line 69, in <module>
  File "mqtt_service.py", line 20, in subscribe
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 707, in subscribe
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 1068, in _connected
MMQTTException: MiniMQTT is not connected`

**Comment by briandye** [comment]
Worked as expected with CircutPy 6.30. Use Mu to erase your disk using REPL to make certain it works… I may dig into what went wrong in 7.3.3 and put a PR in

**Comment by VynDesign** [comment]
Sorry, didn't see this until now. Glad you got it sorted out. Yes, I've only tested this with CircuitPy 6.3.0 per https://github.com/VynDesign/message-board#dependencies
